const BASE_URL = 'http://localhost:8000/api'; // Adjust based on backend URL

const API_ENDPOINTS = {
  UPLOAD_USER_PHOTO: `${BASE_URL}/UploadUserPhoto`,
  GET_ALL_USERS: `${BASE_URL}/GetAllUsers`,
  UPDATE_USER_CURRENT_ROLE: `${BASE_URL}/UpdateUserCurrentRole`,
  UPDATE_BASIC_USER_INFO: `${BASE_URL}/UpdateBasicUserInfo`,
  BASIC_USER_INFO: `${BASE_URL}/BasicUserInfo`,
  REGISTER: `${BASE_URL}/Register`,
  LOGIN: `${BASE_URL}/Login`,
  RECOVER_PASSWORD: `${BASE_URL}/RecoverPassword`,
  CREATE_LOCATION_ENTITY: `${BASE_URL}/CreateLocationEntity`,
  UPDATE_LOCATION_ENTITY: `${BASE_URL}/UpdateLocationEntity`,
  GET_LOCATION_BY_ID: `${BASE_URL}/GetLocationById`,
  GET_ALL_LOCATIONS: `${BASE_URL}/GetAllLocations`,
  CREATE_GRADE_ENTITY: `${BASE_URL}/CreateGradeEntity`,
  UPDATE_GRADE_ENTITY: `${BASE_URL}/UpdateGradeEntity`,
  GET_GRADE_BY_ID: `${BASE_URL}/GetGradeById`,
  GET_ALL_GRADES: `${BASE_URL}/GetAllGrades`,
  GET_WEATHER: `${BASE_URL}/GetWeather`,
  CREATE_CLUB_ENTITY: `${BASE_URL}/CreateClubEntity`,
  UPDATE_CLUB_ENTITY: `${BASE_URL}/UpdateClubEntity`,
  GET_CLUB_BY_ID: `${BASE_URL}/GetClubById`,
  GET_ALL_CLUBS: `${BASE_URL}/GetAllClubs`,
  CREATE_TYPE_ENTITY: `${BASE_URL}/CreateTypeEntity`,
  UPDATE_TYPE_ENTITY: `${BASE_URL}/UpdateTypeEntity`,
  GET_TYPE_BY_ID: `${BASE_URL}/GetTypeById`,
  GET_ALL_TYPES: `${BASE_URL}/GetAllTypes`,
  CREATE_RESULT_ENTITY: `${BASE_URL}/CreateResultEntity`,
  UPDATE_RESULT_ENTITY: `${BASE_URL}/UpdateResultEntity`,
  GET_RESULT_BY_ID: `${BASE_URL}/GetResultById`,
  GET_ALL_RESULTS: `${BASE_URL}/GetAllResults`,
  CREATE_STATE_ENTITY: `${BASE_URL}/CreateStateEntity`,
  UPDATE_STATE_ENTITY: `${BASE_URL}/UpdateStateEntity`,
  GET_STATE_BY_ID: `${BASE_URL}/GetStateById`,
  GET_ALL_STATES: `${BASE_URL}/GetAllStates`,
  CREATE_COMPETITION_ENTITY: `${BASE_URL}/CreateCompetitionEntity`,
  UPDATE_COMPETITION_ENTITY: `${BASE_URL}/UpdateCompetitionEntity`,
  GET_COMPETITION_BY_ID: `${BASE_URL}/GetCompetitionById`,
  GET_ALL_COMPETITIONS: `${BASE_URL}/GetAllCompetitions`,
  CREATE_NOTIFICATION_ENTITY: `${BASE_URL}/CreateNotificationEntity`,
  UPDATE_NOTIFICATION_ENTITY: `${BASE_URL}/UpdateNotificationEntity`,
  GET_NOTIFICATION_BY_ID: `${BASE_URL}/GetNotificationById`,
  GET_ALL_NOTIFICATIONS: `${BASE_URL}/GetAllNotifications`,
  CREATE_ROLE_ENTITY: `${BASE_URL}/CreateRoleEntity`,
  UPDATE_ROLE_ENTITY: `${BASE_URL}/UpdateRoleEntity`,
  GET_ROLE_BY_ID: `${BASE_URL}/GetRoleById`,
  GET_ALL_ROLES: `${BASE_URL}/GetAllRoles`,
  CREATE_TEAM_ENTITY: `${BASE_URL}/CreateTeamEntity`,
  UPDATE_TEAM_ENTITY: `${BASE_URL}/UpdateTeamEntity`,
  GET_TEAM_BY_ID: `${BASE_URL}/GetTeamById`,
  GET_ALL_TEAMS: `${BASE_URL}/GetAllTeams`,
  GET_TEAMS_BY_TRIAL_ID: `${BASE_URL}/GetTeamsByTrialId`,
  CREATE_TRIAL_ENTITY: `${BASE_URL}/CreateTrialEntity`,
  UPDATE_TRIAL_ENTITY: `${BASE_URL}/UpdateTrialEntity`,
  GET_TRIAL_BY_ID: `${BASE_URL}/GetTrialById`,
  GET_ALL_TRIALS: `${BASE_URL}/GetAllTrials`,
  GET_TEAMS_BY_CLUB_ID: `${BASE_URL}/GetTeamsByClubId`,
  GET_USERS_BY_TEAM_ID: `${BASE_URL}/GetUsersByTeamId`
};

export default API_ENDPOINTS;
