version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ea-project
      POSTGRES_PASSWORD: ea-project
      POSTGRES_DB: ea-project
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
