version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ea-project
    volumes:
      - ../database/database.sql:/docker-entrypoint-initdb.d/database.sql