services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ea-project
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
