server:
  port: 3000
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ea-project
    username: ea-project
    password: ea-project
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false